import React, { useState, useEffect, useMemo } from 'react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '../ui/select';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '../ui/card';
import { Badge } from '../ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import { Switch } from '../ui/switch';
import { Loader2, Upload, X, FileText, Image as ImageIcon, Plus } from 'lucide-react';

const EnhancedCreateBuyRequestForm = ({
  defaultCountry = 'ZA',
  provinces = ['Gauteng','Western Cape','KwaZulu-Natal','Eastern Cape','Free State','Limpopo','Mpumalanga','North West','Northern Cape'],
  onCreated
}) => {
  const [species, setSpecies] = useState('');
  const [productType, setProductType] = useState('');
  const [breed, setBreed] = useState('');
  const [qty, setQty] = useState('100');
  const [unit, setUnit] = useState('head');
  const [targetPrice, setTargetPrice] = useState('');
  const [province, setProvince] = useState('');
  const [country] = useState(defaultCountry);
  const [expiresAt, setExpiresAt] = useState('');
  const [notes, setNotes] = useState('');
  const [loading, setLoading] = useState(false);

  // AI Enhancement toggles
  const [enableAiEnhancements, setEnableAiEnhancements] = useState(true);
  const [autoGenerateDescription, setAutoGenerateDescription] = useState(false);

  // AI Features state
  const [priceSuggestions, setPriceSuggestions] = useState(null);
  const [loadingPrices, setLoadingPrices] = useState(false);
  const [generatedDescription, setGeneratedDescription] = useState('');
  const [loadingDescription, setLoadingDescription] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState(null);

  // Dynamic options from catalog
  const [speciesOpts, setSpeciesOpts] = useState([]);
  const [ptypeOpts, setPtypeOpts] = useState([]);
  const [breedOpts, setBreedOpts] = useState([]);
  const [unitOpts, setUnitOpts] = useState([
    { value: 'head', label: 'Head' },
    { value: 'dozen', label: 'Dozen (eggs)' },
    { value: 'kg', label: 'kg (meat/fish)' }
  ]);

  // Set default expiry date (14 days from now)
  useEffect(() => {
    const defaultDate = new Date();
    defaultDate.setDate(defaultDate.getDate() + 14);
    setExpiresAt(defaultDate.toISOString().split('T')[0]);
  }, []);

  // Fetch species on mount
  useEffect(() => {
    const fetchSpecies = async () => {
      try {
        const res = await fetch(`${process.env.REACT_APP_BACKEND_URL}/api/species`);
        const data = await res.json();
        const opts = (data?.species || data || []).map(s => ({ 
          value: s.code || s.id || s.name, 
          label: s.name 
        }));
        setSpeciesOpts(opts);
      } catch (error) {
        console.error('Error fetching species:', error);
      }
    };
    
    fetchSpecies();
  }, []);

  // Fetch product types when species changes
  useEffect(() => {
    if (!species) { 
      setPtypeOpts([]); 
      setProductType(''); 
      return; 
    }
    
    const fetchProductTypes = async () => {
      try {
        const res = await fetch(`${process.env.REACT_APP_BACKEND_URL}/api/product-types?species=${encodeURIComponent(species)}`);
        const data = await res.json();
        const opts = (data?.product_types || data || []).map(p => ({ 
          value: p.code || p.id || p.name, 
          label: p.name 
        }));
        setPtypeOpts(opts);
        
        // Update units based on product type
        if (data?.units_for_product_type) {
          setUnitOpts(data.units_for_product_type.map(u => ({ value: u.value, label: u.label })));
        }
      } catch (error) {
        console.error('Error fetching product types:', error);
      }
    };
    
    fetchProductTypes();
  }, [species]);

  // Fetch breeds when species changes
  useEffect(() => {
    if (!species) { 
      setBreedOpts([]); 
      setBreed(''); 
      return; 
    }
    
    const fetchBreeds = async () => {
      try {
        const res = await fetch(`${process.env.REACT_APP_BACKEND_URL}/api/species/${encodeURIComponent(species)}/breeds`);
        const data = await res.json();
        const opts = (data?.breeds || data || []).map(b => ({ 
          value: b.code || b.id || b.name, 
          label: b.name 
        }));
        setBreedOpts(opts);
      } catch (error) {
        console.error('Error fetching breeds:', error);
      }
    };
    
    fetchBreeds();
  }, [species]);

  // Update default unit based on product type
  useEffect(() => {
    if (!productType) return;
    if (/EGG/i.test(productType)) setUnit('dozen');
    else if (/MEAT|FISH/i.test(productType)) setUnit('kg');
    else setUnit('head');
  }, [productType]);

  // Get AI price suggestions when key fields change
  useEffect(() => {
    if (enableAiEnhancements && species && productType && province) {
      fetchPriceSuggestions();
    }
  }, [species, productType, province, qty, unit, enableAiEnhancements]);

  const fetchPriceSuggestions = async () => {
    if (!species || !productType) return;
    
    setLoadingPrices(true);
    try {
      const token = localStorage.getItem('token');
      const params = new URLSearchParams({
        species,
        product_type: productType,
        ...(breed && { breed }),
        ...(province && { province }),
        ...(qty && { quantity: qty }),
        ...(unit && { unit })
      });

      const res = await fetch(`${process.env.REACT_APP_BACKEND_URL}/api/buy-requests/price-suggestions?${params}`, {
        headers: {
          ...(token ? { 'Authorization': `Bearer ${token}` } : {})
        }
      });

      if (res.ok) {
        const data = await res.json();
        setPriceSuggestions(data.suggestions);
      }
    } catch (error) {
      console.error('Error fetching price suggestions:', error);
    } finally {
      setLoadingPrices(false);
    }
  };

  const generateDescription = async () => {
    setLoadingDescription(true);
    try {
      const token = localStorage.getItem('token');
      
      const res = await fetch(`${process.env.REACT_APP_BACKEND_URL}/api/buy-requests/auto-description`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { 'Authorization': `Bearer ${token}` } : {})
        },
        body: JSON.stringify({
          species,
          product_type: productType,
          breed,
          quantity: Number(qty),
          unit,
          province,
          target_price: targetPrice ? Number(targetPrice) : null,
          notes: notes || null
        })
      });

      if (res.ok) {
        const data = await res.json();
        setGeneratedDescription(data.description || '');
        if (data.description) {
          setNotes(data.description);
        }
      }
    } catch (error) {
      console.error('Error generating description:', error);
    } finally {
      setLoadingDescription(false);
    }
  };

  const isValid = useMemo(() => {
    return species && productType && qty && unit && province && expiresAt;
  }, [species, productType, qty, unit, province, expiresAt]);

  const handleSubmit = async () => {
    if (!isValid) return;
    
    setLoading(true);
    try {
      const payload = {
        species,
        product_type: productType,
        breed: breed || null,
        qty: Number(qty),
        unit,
        target_price: targetPrice ? Number(targetPrice) : null,
        province,
        country,
        expires_at: new Date(expiresAt).toISOString(),
        notes: notes || null,
        enable_ai_enhancements: enableAiEnhancements,
        auto_generate_description: autoGenerateDescription
      };

      const token = localStorage.getItem('token');
      
      const endpoint = enableAiEnhancements ? 
        `${process.env.REACT_APP_BACKEND_URL}/api/buy-requests/enhanced` :
        `${process.env.REACT_APP_BACKEND_URL}/api/buy-requests`;
      
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { 'Authorization': `Bearer ${token}` } : {})
        },
        body: JSON.stringify(payload)
      });

      const result = await res.json();
      
      if (!res.ok) {
        throw new Error(result.error || 'Failed to create request');
      }

      // Store AI analysis for display
      if (result.ai_analysis) {
        setAiAnalysis(result);
      }

      // Show success message
      const toast = document.createElement('div');
      toast.className = 'fixed top-4 right-4 bg-green-500 text-white p-4 rounded-md z-50 max-w-md';
      toast.innerHTML = `
        <div class="font-semibold">Buy Request Created Successfully!</div>
        <div class="text-sm mt-1">
          ${enableAiEnhancements ? 'AI-enhanced features enabled.' : ''} 
          Sellers in your area will be notified.
        </div>
      `;
      document.body.appendChild(toast);
      setTimeout(() => document.body.removeChild(toast), 4000);

      // Reset form
      setQty('100');
      setTargetPrice('');
      setNotes('');
      setPriceSuggestions(null);
      setGeneratedDescription('');
      setAiAnalysis(null);
      
      if (onCreated) {
        onCreated(result.id);
      }
      
    } catch (error) {
      const toast = document.createElement('div');
      toast.className = 'fixed top-4 right-4 bg-red-500 text-white p-4 rounded-md z-50';
      toast.textContent = error.message;
      document.body.appendChild(toast);
      setTimeout(() => document.body.removeChild(toast), 3000);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Target className="h-5 w-5" />
            Create Buy Request
            {enableAiEnhancements && (
              <Badge variant="secondary" className="bg-purple-100 text-purple-800">
                <Sparkles className="h-3 w-3 mr-1" />
                AI Enhanced
              </Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* AI Enhancement Controls */}
          <div className="border rounded-lg p-4 bg-gradient-to-r from-purple-50 to-blue-50">
            <div className="flex items-center justify-between mb-3">
              <div>
                <h4 className="font-semibold text-sm">AI Enhancements</h4>
                <p className="text-xs text-gray-600">Enable smart features powered by AI</p>
              </div>
              <Switch
                checked={enableAiEnhancements}
                onCheckedChange={setEnableAiEnhancements}
              />
            </div>
            
            {enableAiEnhancements && (
              <div className="grid grid-cols-1 gap-3">
                <div className="flex items-center justify-between">
                  <span className="text-sm">Auto-generate description</span>
                  <Switch
                    checked={autoGenerateDescription}
                    onCheckedChange={setAutoGenerateDescription}
                    size="sm"
                  />
                </div>
              </div>
            )}
          </div>

          {/* Species, Product Type, Breed */}
          <div className="grid md:grid-cols-3 gap-3">
            <div>
              <Label>Species *</Label>
              <Select value={species} onValueChange={setSpecies}>
                <SelectTrigger>
                  <SelectValue placeholder="Select species" />
                </SelectTrigger>
                <SelectContent>
                  {speciesOpts.map(o => (
                    <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Product Type *</Label>
              <Select value={productType} onValueChange={setProductType} disabled={!species}>
                <SelectTrigger>
                  <SelectValue placeholder="Live, Day-old, Eggs…" />
                </SelectTrigger>
                <SelectContent>
                  {ptypeOpts.map(o => (
                    <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Breed (optional)</Label>
              <Select value={breed} onValueChange={setBreed} disabled={!species || breedOpts.length === 0}>
                <SelectTrigger>
                  <SelectValue placeholder={breedOpts.length ? 'Select breed' : 'No breeds'} />
                </SelectTrigger>
                <SelectContent>
                  {breedOpts.map(o => (
                    <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Quantity, Unit, Target Price, Expires */}
          <div className="grid md:grid-cols-4 gap-3">
            <div>
              <Label>Quantity *</Label>
              <Input 
                type="number" 
                value={qty} 
                onChange={(e) => setQty(e.target.value)}
                min="1"
              />
            </div>
            <div>
              <Label>Unit *</Label>
              <Select value={unit} onValueChange={setUnit}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {unitOpts.map(o => (
                    <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <Label>Target Price (per unit)</Label>
                {loadingPrices && <Loader2 className="h-3 w-3 animate-spin" />}
              </div>
              <Input 
                type="number" 
                placeholder="e.g. 1800" 
                value={targetPrice} 
                onChange={(e) => setTargetPrice(e.target.value)}
                min="0"
                step="0.01"
              />
              {priceSuggestions && (
                <div className="mt-2 p-2 bg-green-50 rounded text-xs">
                  <div className="flex items-center gap-1 font-semibold text-green-800">
                    <DollarSign className="h-3 w-3" />
                    AI Suggestion: R{priceSuggestions.suggested_price}
                  </div>
                  <div className="text-green-600">
                    Range: R{priceSuggestions.price_range?.min} - R{priceSuggestions.price_range?.max}
                  </div>
                  {priceSuggestions.confidence && (
                    <div className="text-green-600">
                      Confidence: {priceSuggestions.confidence}%
                    </div>
                  )}
                </div>
              )}
            </div>
            <div>
              <Label>Expires *</Label>
              <Input 
                type="date" 
                value={expiresAt} 
                onChange={(e) => setExpiresAt(e.target.value)} 
              />
            </div>
          </div>

          {/* Province, Country */}
          <div className="grid md:grid-cols-3 gap-3">
            <div className="md:col-span-2">
              <div className="flex items-center gap-2">
                <Label>Province *</Label>
                <MapPin className="h-3 w-3 text-gray-500" />
              </div>
              <Select value={province} onValueChange={setProvince}>
                <SelectTrigger>
                  <SelectValue placeholder="Select province" />
                </SelectTrigger>
                <SelectContent>
                  {provinces.map(p => (
                    <SelectItem key={p} value={p}>{p}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Country</Label>
              <Input value={country} disabled />
            </div>
          </div>

          {/* Notes with AI Enhancement */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <Label>Notes (optional)</Label>
              {enableAiEnhancements && (
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  onClick={generateDescription}
                  disabled={loadingDescription || !species || !productType}
                  className="text-xs"
                >
                  {loadingDescription ? (
                    <>
                      <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <MessageSquare className="h-3 w-3 mr-1" />
                      AI Generate
                    </>
                  )}
                </Button>
              )}
            </div>
            <Textarea 
              rows={4} 
              placeholder="Any specifications (weight range, sex, vaccination requirements)…" 
              value={notes} 
              onChange={(e) => setNotes(e.target.value)} 
            />
            {generatedDescription && (
              <div className="mt-2 p-2 bg-blue-50 rounded text-xs">
                <div className="font-semibold text-blue-800 mb-1">AI Generated Description:</div>
                <div className="text-blue-700">{generatedDescription}</div>
              </div>
            )}
          </div>
        </CardContent>
        <CardFooter>
          <Button onClick={handleSubmit} disabled={!isValid || loading} className="w-full">
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                {enableAiEnhancements ? 'Creating Enhanced Request…' : 'Posting…'}
              </>
            ) : (
              <>
                {enableAiEnhancements ? (
                  <Sparkles className="mr-2 h-4 w-4" />
                ) : (
                  <Target className="mr-2 h-4 w-4" />
                )}
                {enableAiEnhancements ? 'Create AI-Enhanced Request' : 'Post Buy Request'}
              </>
            )}
          </Button>
        </CardFooter>
      </Card>

      {/* AI Analysis Results */}
      {aiAnalysis && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              <Sparkles className="h-5 w-5 text-purple-600" />
              AI Analysis Results
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {aiAnalysis.ai_analysis && (
              <div className="border rounded-lg p-3">
                <h4 className="font-semibold text-sm mb-2">Content Analysis</h4>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="font-medium">Category:</span> 
                    <Badge className="ml-2" variant={aiAnalysis.ai_analysis.category === 'safe' ? 'default' : 'destructive'}>
                      {aiAnalysis.ai_analysis.category}
                    </Badge>
                  </div>
                  <div>
                    <span className="font-medium">Confidence:</span> {aiAnalysis.ai_analysis.confidence}%
                  </div>
                </div>
              </div>
            )}

            {aiAnalysis.categorization && (
              <div className="border rounded-lg p-3">
                <h4 className="font-semibold text-sm mb-2">Smart Categorization</h4>
                <div className="flex flex-wrap gap-1">
                  {aiAnalysis.categorization.tags?.map((tag, index) => (
                    <Badge key={index} variant="outline" className="text-xs">
                      {tag}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            {aiAnalysis.location_data?.coordinates && (
              <div className="border rounded-lg p-3">
                <h4 className="font-semibold text-sm mb-2">Location Data</h4>
                <div className="text-sm text-gray-600">
                  <div>Address: {aiAnalysis.location_data.formatted_address}</div>
                  <div className="text-xs mt-1">
                    Coordinates: {aiAnalysis.location_data.coordinates.latitude.toFixed(4)}, {aiAnalysis.location_data.coordinates.longitude.toFixed(4)}
                  </div>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default EnhancedCreateBuyRequestForm;